name: Validate posts.json
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check JSON validity
        run: node -e "JSON.parse(require('fs').readFileSync('posts.json','utf8')); console.log('posts.json OK');"
      - name: Check minimal schema
        run: |
          node -e "const fs=require('fs');const a=JSON.parse(fs.readFileSync('posts.json','utf8'));if(!Array.isArray(a)||!a.length) process.exit(1); for(const x of a){ if(!x.id||!x.title||!x.date||!x.content){ console.error('Missing fields',x); process.exit(2);} } console.log('schema OK');"
